config/routes.rb
Webshop::Application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'

  namespace :admin do
    resources :products do
      resources :product_images
    end
    resources :brands
    resources :categories
  end

  resources :users
  resources :sessions
  resources :products
  resources :categories, :only => :show
  resources :brands, :only => :show

  root to: 'pages#home'
  resources :pages do
    collection do
      get 'test'
    end
  end

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  attr_accessible :slug, :name

  before_save :create_slug

  has_many :products

  def create_slug
    self.slug = self.name.parameterize
  end

  def self.all_brands
    Brand.order('name')
  end
end

app/controllers/admin/brands_controller.rb
class Admin::BrandsController < ApplicationController

  layout 'admin'
  before_filter :authorize!

  # GET /admin/brands
  # GET /admin/brands.json
  def index
    @admin_brands = Brand.all_brands

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_brands }
    end
  end


  # GET /admin/brands/new
  # GET /admin/brands/new.json
  def new
    @admin_brand = Brand.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_brand }
    end
  end

  # GET /admin/brands/1/edit
  def edit
    @admin_brand = Brand.find(params[:id])
  end

  # POST /admin/brands
  # POST /admin/brands.json
  def create
    @admin_brand = Brand.new(params[:brand])

    respond_to do |format|
      if @admin_brand.save
        format.html { redirect_to admin_brands_url, notice: 'Brand was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /admin/brands/1
  # PUT /admin/brands/1.json
  def update
    @admin_brand = Brand.find(params[:id])

    respond_to do |format|
      if @admin_brand.update_attributes(params[:brand])
        format.html { redirect_to admin_brands_url, notice: 'Brand was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/brands/1
  # DELETE /admin/brands/1.json
  def destroy
    @admin_brand = Brand.find(params[:id])
    @admin_brand.destroy

    respond_to do |format|
      format.html { redirect_to admin_brands_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def show
    @brand = Brand.find(params[:id])

    respond_to do |format|
      format.html
    end
  end
end

app/helpers/admin/brands_helper.rb
module Admin::BrandsHelper
end

app/views/admin/brands/_form.html.erb
<div class="row">
  <div class="twelve columns">

    <%= form_for [:admin, @admin_brand] do |f| %>
      <% if @admin_brand.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@admin_brand.errors.count, "error") %> </h2>
          <ul>
            <% @admin_brand.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name %>
      </div>
      <div class="actions">
        <%= f.submit "Save brand", :class => "rounded button right" %>
      </div>
    <% end %>

  </div>
</div>

app/views/admin/brands/edit.html.erb
<header class="row header"> <!-- Header -->
<div class="twelve columns">
  <div class="row">
    <%= link_to admin_brands_path do %>
      &larr; Bact to All Brands List
    <% end %>
  </div>
</div>

<div class="twelve columns">
  <h1>Edit: <%= @admin_brand.name %></h1>
  <h4 class="subheader">Edit brand. Delete brand.</h4>
  <div class="actions">
    <%= link_to 'Delete this item!', admin_brand_path(@admin_brand), method: :delete, data: { confirm: 'Are you sure?' }, class: 'tiny button alert' %>
  </div>
</div>
</header> <!-- End Header -->

<%= render 'form' %>

app/views/admin/brands/index.html.erb
<header class="row header"> <!-- header -->
<div class="twelve columns">
  <h1>Brands List</h1>
  <h4 class="subheader">Select brand to edit. Delete brand.</h4>
  <%= link_to '+ New Brand', new_admin_brand_path, class: 'small button' %>
</div>
</header> <!-- end header -->

<div class="row">
  <table class="twelve">
    <thead>
      <tr>
        <th>Brand Name</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @admin_brands.each do |admin_brand| %>
        <tr>
          <td><%= link_to admin_brand.name, edit_admin_brand_path(admin_brand) %></td>
          <td><%= link_to 'Destroy', admin_brand_path(admin_brand), method: :delete, data: { confirm: 'Are you sure?' }, class: 'label radius alert' %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/brands/new.html.erb
<header class="row header"> <!-- Header -->
  <div class="twelve columns">
    <h1>New Brand</h1>
    <h4 class="subheader">Add New Brand.</h4>
    <div class="row">
      <div class="twelve columns">
        <%= link_to admin_brands_path do %>
          &larr; Bact to All Brands List
        <% end %>
      </div>
    </div>
  </div>
</header> <!-- End Header -->

<%= render 'form' %>