config/routes.rb
Webshop::Application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'

  namespace :admin do
    resources :products do
      resources :product_images
    end
    resources :brands
    resources :categories
  end

  resources :users
  resources :sessions
  resources :products
  resources :categories, :only => :show
  resources :brands, :only => :show

  root to: 'pages#home'
  resources :pages do
    collection do
      get 'test'
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  before_save :create_slug

  has_many :products

  def create_slug
    self.slug = self.name.parameterize
  end

  def self.all_categories
    Category.order('name')
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  layout 'admin'
  before_filter :authorize!

  # GET /admin/categories
  # GET /admin/categories.json
  def index
    @admin_categories = Category.all_categories

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_categories }
    end
  end


  # GET /admin/categories/new
  # GET /admin/categories/new.json
  def new
    @admin_category =  Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_category }
    end
  end

  # GET /admin/categories/1/edit
  def edit
    @admin_category = Category.find(params[:id])
  end

  # POST /admin/categories
  # POST /admin/categories.json
  def create
    @admin_category = Category.new(params[:category])

    respond_to do |format|
      if @admin_category.save
        format.html { redirect_to admin_categories_url, notice: 'Category was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /admin/categories/1
  # PUT /admin/categories/1.json
  def update
    @admin_category = Category.find(params[:id])

    respond_to do |format|
      if @admin_category.update_attributes(params[:category])
        format.html { redirect_to admin_categories_url, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/categories/1
  # DELETE /admin/categories/1.json
  def destroy
    @admin_category = Category.find(params[:id])
    @admin_category.destroy

    respond_to do |format|
      format.html { redirect_to admin_categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<div class="row">
  <div class="twelve columns">

    <%= form_for [:admin, @admin_category] do |f| %>
      <% if @admin_category.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@admin_category.errors.count, "error") %> </h2>
          <ul>
            <% @admin_category.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name %>
      </div>
      <div class="actions">
        <%= f.submit "Save category", :class => "rounded button right" %>
      </div>
    <% end %>

  </div>
</div>

app/views/admin/categories/edit.html.erb
<header class="row header"> <!-- Header -->
<div class="twelve columns">
  <div class="row">
    <%= link_to admin_categories_path do %>
      &larr; Bact to All Categories List
    <% end %>
  </div>
</div>

<div class="twelve columns">
  <h1>Edit: <%= @admin_category.name %></h1>
  <h4 class="subheader">Edit category. Delete category.</h4>
  <div class="actions">
    <%= link_to 'Delete this item!', admin_category_path(@admin_category), method: :delete, data: { confirm: 'Are you sure?' }, class: 'tiny button alert' %>
  </div>
</div>
</header> <!-- End Header -->

<%= render 'form' %>

app/views/admin/categories/index.html.erb
<header class="row header"> <!-- header -->
<div class="twelve columns">
  <h1>Categories List</h1>
  <h4 class="subheader">Select category to edit. Delete category.</h4>
  <%= link_to '+ New Category', new_admin_category_path, class: 'small button' %>
</div>
</header> <!-- end header -->

<div class="row">
  <table class="twelve">
    <thead>
      <tr>
        <th>Category Name</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @admin_categories.each do |admin_category| %>
        <tr>
          <td><%= link_to admin_category.name, edit_admin_category_path(admin_category) %></td>
          <td><%= link_to 'Destroy', admin_category_path(admin_category), method: :delete, data: { confirm: 'Are you sure?' }, class: 'label radius alert' %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/categories/new.html.erb
<header class="row header"> <!-- Header -->
  <div class="twelve columns">
    <h1>New Category</h1>
    <h4 class="subheader">Add New Category.</h4>
    <div class="row">
      <div class="twelve columns">
        <%= link_to admin_categories_path do %>
          &larr; Bact to all categories List
        <% end %>
      </div>
    </div>
  </div>
</header> <!-- End Header -->

<%= render 'form' %>