config/routes.rb
Webshop::Application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'

  namespace :admin do
    resources :products do
      resources :product_images
    end
    resources :brands
    resources :categories
  end

  resources :users
  resources :sessions
  resources :products
  resources :categories, :only => :show
  resources :brands, :only => :show

  root to: 'pages#home'
  resources :pages do
    collection do
      get 'test'
    end
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, 
                  :title, 
                  :category_id, 
                  :brand_id,
                  :price

  validates :title, :presence => true
  validates :description, :presence => true
  validates :price, :presence => true,
            :numericality => true,
            :format => { :with => /^\d{1,4}(\.\d{0,2})?$/ }

  has_many :product_images
  belongs_to :category
  belongs_to :brand

  # get featuring image
  def featuring_image(size)
    product_images.first.image_url(size) if product_images.first
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  layout 'admin'
  before_filter :authorize!

  # GET /admin/products
  # GET /admin/products.json
  def index
    @admin_products = Product.order('updated_at DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_products }
    end
  end

  # GET /admin/products/new
  # GET /admin/products/new.json
  def new
    @admin_product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_product }
    end
  end

  # GET /admin/products/1/edit
  def edit
    @admin_product = Product.find(params[:id])
  end

  # POST /admin/products
  # POST /admin/products.json
  def create
    @admin_product = Product.new(params[:product])

    respond_to do |format|
      if @admin_product.save
        format.html { redirect_to admin_products_path, notice: 'Product was successfully created.' }
        format.json { render json: @admin_product, status: :created, location: @admin_product }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/products/1
  # PUT /admin/products/1.json
  def update
    @admin_product = Product.find(params[:id])

    respond_to do |format|
      if @admin_product.update_attributes(params[:product])
        format.html { redirect_to admin_products_path, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/products/1
  # DELETE /admin/products/1.json
  def destroy
    @admin_product = Product.find(params[:id])
    @admin_product.destroy

    respond_to do |format|
      format.html { redirect_to admin_products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all

    respond_to do |format|
      format.html
    end
  end

  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html
    end
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<div class="row">
  <div class="twelve columns">

    <%= form_for [:admin, @admin_product] do |f| %>
      <% if @admin_product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@admin_product.errors.count, "error") %> </h2>

          <ul>
            <% @admin_product.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :title %><br />
        <%= f.text_field :title %>
      </div>

      <div class="field">
        <%= f.label :description %><br />
        <%= f.text_area :description, rows: 3, class: 'ckeditor' %>
      </div>

      <div class="field">
        <%= f.label :price %><br />
        <%= f.text_field :price %>
      </div>

      <div class="field">
        <%= f.label :category %><br />
        <%= f.collection_select :category_id, Category.all_categories, :id, :name, :include_blank => true %>
      </div>

      <div class="field">
        <%= f.label :brand %><br />
        <%= f.collection_select :brand_id, Brand.all_brands, :id, :name, :include_blank => true %>
      </div>

      <div class="actions">
        <%= f.submit "Save product", :class => "rounded button right" %>
      </div>
    <% end %>

  </div>
</div>

app/views/admin/products/_product.html.erb
<div class="adminProductWrapper">
  <h4><%= link_to product.title, edit_admin_product_path(product) %></h4>
  <p><%= product.description %></p>
</div>

app/views/admin/products/edit.html.erb
<header class="row header"> <!-- Header -->
<div class="twelve columns">
  <div class="row">
    <%= link_to admin_products_path do %>
      &larr; Bact to All Products List
    <% end %>
  </div>
</div>

<div class="twelve columns">
  <h1>Edit: <%= @admin_product.title %></h1>
  <h4 class="subheader">Edit product info. Delete product. Add or delete product images.</h4>
  <div class="actions">
    <%= link_to 'Delete this item!', admin_product_path(@admin_product), method: :delete, data: { confirm: 'Are you sure?' }, class: 'tiny button alert' %>
  </div>
</div>
</header> <!-- End Header -->

<%= render 'form' %>

<%= render 'admin/product_images/form' %>

<div class="twelve columns">
  <div class="row">
    <div class="twelve columns productImages admin">
      <div id="product_images" class="row">
        <% @admin_product.product_images.each do |product_image| %>
          <%= render '/admin/product_images/product_thumb', image: product_image %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
<header class="row header"> <!-- header -->
  <div class="twelve columns">
    <h1>All products</h1>
    <h4 class="subheader">Select item from list to edit or upload image for it.</h4>
    <%= link_to '+ New Product', new_admin_product_path, class: 'small button' %>
  </div>
  </header> <!-- end header -->


<div class="row">
  <div class="twelve columns">
    <div class="row">
      <% @admin_products.each do |product| %>
        <%= render '/products/product', product: product %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<header class="row header"> <!-- Header -->
  <div class="twelve columns">
    <h1>New Product</h1>
    <h4 class="subheader">Add New Product.</h4>
    <div class="row">
      <div class="twelve columns">
        <%= link_to admin_products_path do %>
          &larr; Bact to All Products List
        <% end %>
      </div>
    </div>
  </div>
</header> <!-- End Header -->

<%= render 'form' %>