config/routes.rb
Webshop::Application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'

  namespace :admin do
    resources :products do
      resources :product_images
    end
    resources :brands
    resources :categories
  end

  resources :users
  resources :sessions
  resources :products
  resources :categories, :only => :show
  resources :brands, :only => :show

  root to: 'pages#home'
  resources :pages do
    collection do
      get 'test'
    end
  end

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  attr_accessible :slug, :name

  before_save :create_slug

  has_many :products

  def create_slug
    self.slug = self.name.parameterize
  end

  def self.all_brands
    Brand.order('name')
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  before_save :create_slug

  has_many :products

  def create_slug
    self.slug = self.name.parameterize
  end

  def self.all_categories
    Category.order('name')
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, 
                  :title, 
                  :category_id, 
                  :brand_id,
                  :price

  validates :title, :presence => true
  validates :description, :presence => true
  validates :price, :presence => true,
            :numericality => true,
            :format => { :with => /^\d{1,4}(\.\d{0,2})?$/ }

  has_many :product_images
  belongs_to :category
  belongs_to :brand

  # get featuring image
  def featuring_image(size)
    product_images.first.image_url(size) if product_images.first
  end
end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
  belongs_to :product
  attr_accessible :image, :remote_image_url

  mount_uploader :image, ImageUploader

  def errors_to_json
    errors.full_messages.to_json
  end

  #after_save :enqueue_image

  #def enqueue_image
    #ImageWorker.perform_async(id, remote_image_net_url) if remote_image_net_url.present?
  #end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  # In order to crate new user provide email, password and password_confirmation fields

  attr_accessible :email, :password, :password_confirmation
  validates :email, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

private
  
  def current_user
    @current_user = User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize!
    redirect_to root_url, alert: "You are not authorized to access this area!" if current_user.nil?
  end

end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def show
    @brand = Brand.find(params[:id])

    respond_to do |format|
      format.html
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end

  def test
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all

    respond_to do |format|
      format.html
    end
  end

  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    # Login page
    if session[:user_id]
      redirect_to admin_products_url, notice: "You are already logged in!"
    end
  end

  def create
    user = User.find_by_email(params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to admin_products_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid!"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/admin/brands_helper.rb
module Admin::BrandsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/upload_helper.rb
module UploadHelper
  def s3_uploader_form(options = {}, &block)
    uploader = S3Uploader.new(options)
    form_tag(uploader.url, uploader.form_options) do
      uploader.fields.map do |name, value|
        hidden_field_tag(name, value)
      end.join.html_safe + capture(&block)
    end
  end

  class S3Uploader
    def initialize(options)
      @options = options.reverse_merge(
        id: "fileupload",
        aws_access_key_id: ENV["AWS_ACCESS_KEY_ID"],
        aws_secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"],
        bucket: ENV["AWS_S3_BUCKET"],
        acl: "public-read",
        expiration: 10.hours.from_now,
        max_file_size: 500.megabytes,
        as: "file"
      )
    end

    def form_options
      {
        id: @options[:id],
        method: "post",
        authenticity_token: false,
        multipart: true,
        data: {
        post: @options[:post],
        as: @options[:as]
      }
      }
    end

    def fields
      {
        :key => key,
        :acl => @options[:acl],
        :policy => policy,
        :signature => signature,
        "AWSAccessKeyId" => @options[:aws_access_key_id],
        "Content-Type" => ""
      }
    end

    def key
      @key ||= "uploads/#{SecureRandom.hex}/${filename}"
    end

    def url
      "https://#{@options[:bucket]}.s3.amazonaws.com/"
    end

    def policy
      Base64.encode64(policy_data.to_json).gsub("\n", "")
    end

    def policy_data
      {
        expiration: @options[:expiration],
        conditions: [
          ["starts-with", "$utf8", ""],
          ["starts-with", "$key", ""],
          ["starts-with", "$Content-Type", ""],
          ["content-length-range", 0, @options[:max_file_size]],
          {bucket: @options[:bucket]},
          {acl: @options[:acl]}
      ]
      }
    end

    def signature
      Base64.encode64(
        OpenSSL::HMAC.digest(
          OpenSSL::Digest::Digest.new('sha1'),
          @options[:aws_secret_access_key], policy
      )
      ).gsub("\n", "")
    end

  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_admin_navigation.html.erb
<div class="contain-to-grid fixed" id="top_navigation"> <!-- Navigation-->
  <nav class="top-bar fixed">
  <ul>
    <li class="name"><h1><a href="/admin/products">Admin area</a></h1></li>
    <li class="toggle-topbar"><a href="#"></a></li>
  </ul>

  <section>
    <ul class="left">
      <li class="has-dropdown">
      <a href="#">Manage Products</a>
      <ul class="dropdown">
        <li> <%= link_to "List products", admin_products_path %> </li>
        <li> <%= link_to "Add New Product", new_admin_product_path %> </li>
      </ul>
      </li>
      <li> <%= link_to "Manage Brands", admin_brands_path %> </li>
      <li> <%= link_to "Manage Categories", admin_categories_path %> </li>
    </ul>

    <ul class="right">
      <% if current_user %>
        <li>
          <%= link_to "Logout(Admin)", logout_path %>
        </li>
      <% end %>
    </ul>
  </section>
  </nav>
</div> <!-- End Navigation -->

app/views/layouts/_footer.html.erb
<%= render 'layouts/horizontal_divider' %>

<footer class="row footer"> <!-- Footer -->
  <div class="twelve columns">
    <div class="row">
      <div class="three columns">
        <p>&copy; Copyright webshop 2012.</p>
      </div>

      <div class="four columns">
        <ul>
          <% Category.find_each do |category| %>
            <li> <%= link_to category.name, category %> </li>
          <% end %>
        </ul>
      </div>

      <div class="five columns">
        <ul class="link-list right">
          <li><a href="#">About Us</a></li>
          <li><a href="#">Privacy</a></li>
          <li><a href="#">Terms and Conditions</a></li>
          <li><a href="#">Blog</a></li>
        </ul>
      </div>

    </div>
  </div>
</footer> <!-- End Footer -->

app/views/layouts/_horizontal_divider.html.erb
<div class="row">
  <div class="twelve columns">      
    <hr>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<div class="contain-to-grid fixed" id="top_navigation"> <!-- Navigation-->
  <nav class="top-bar fixed">
  <ul>
    <li class="name"><h1><a href="/">StoreName</a></h1></li>
    <li class="toggle-topbar"><a href="#"></a></li>
  </ul>

  <section>
  <ul class="left">
    <li><a href="/">Trending</a></li>

    <li class="has-dropdown">
    <a href="#">Categories</a>
    <ul class="dropdown">
      <% Category.find_each do |category| %>
        <li><%= link_to category.name, category %></li>
      <% end %>
    </ul>
    </li>

    <li class="has-dropdown">
    <a href="#">Brands</a>
    <ul class="dropdown">
      <% Brand.find_each do |brand| %>
        <li><%= link_to brand.name, brand %></li>
      <% end %>
    </ul>
    </li>

  </ul>

  <ul class="right">
    <li><a href="#">Cart(0)</a></li>
  </ul>
  </section>
  </nav>
</div> <!-- End Navigation -->

app/views/layouts/_notice_messages.html.erb
<div class="row" id="notice_messages_container">
  <div class="twelve columns">
    <% flash.each do |type, message| %>
      <%= content_tag :div, :class => "alert-box #{type}" do %>
        <%= message %>
        <a class="close" href="">×</a>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 6 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />
	
	<!-- Uncomment to make IE8 render like IE7 -->
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
	
	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	
	<title><%= content_for?(:title) ? yield(:title) : "Webshop" %></title>
  
	<!-- Included CSS Files -->
	<%= stylesheet_link_tag    "application" %>
	
	<!-- Included JS Files  -->
	<%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render 'layouts/admin_navigation' %>
  <%= render 'layouts/notice_messages' %>
  <div id="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 6 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />
	
	<!-- Uncomment to make IE8 render like IE7 -->
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
	
	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	
	<title><%= content_for?(:title) ? yield(:title) : "Webshop" %></title>
  
	<!-- Included CSS Files -->
	<%= stylesheet_link_tag    "application" %>
	
	<!-- Included JS Files  -->
	<%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/notice_messages' %>
  <div class="" id="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>

</html>

app/views/pages/home.html.erb
<header class="row header"> <!-- Header -->
  <div class="twelve columns">
    <h1>Welcome to LenchyLux</h1>
    <h4 class="subheader">Tagline Everything you need to know to build for the future.</h4>
  </div>
</header> <!-- End Header -->

<div class="row"> <!-- Thumbanails -->
  <div class="twelve columns">
    <div id="featured_products" class="row">
      <% Product.limit(4).each do |product| %>
        <%= render product %>
      <% end %>
    </div>
  </div>
</div> <!-- End Thumbnails -->

<div class="row">
  <div class="twelve columns">
    <h5>
      <%= link_to products_path do %>
        Explore All Products &rarr;
      <% end %>
    </h5>
  </div>
</div>

<%= render 'layouts/horizontal_divider' %>
<div class="row about">
  <div class="six columns"> <!-- Left column -->
    <div class="panel">
      <h4>About this webshop</h4>
      <h5 class="subheader">Fusce ullamcorper mauris in eros dignissim molestie posuere felis blandit. Aliquam erat volutpat. Mauris ultricies posuere vehicula. Sed sit amet posuere erat. Quisque in ipsum non augue euismod dapibus non et eros. Pellentesque consectetur tempus mi iaculis bibendum. Ut vel dolor sed eros tincidunt volutpat ac eget leo.</h5>
      <a href="#">Read More About Us →</a>
    </div>

    <div class="row">
      <div class="six mobile-two columns">
        <div class="panel">
          <h5>Contact Us</h5>
          <h6 class="subheader">Send message from our contact form.</h6>
          <a href="#" class="small button">Contact us</a>
        </div>
      </div>

      <div class="six mobile-two columns">
        <div class="panel social-box">
          <h5>Follow Us</h5>
          <h6 class="subheader">Be Social.</h6>
          <ul class="inline-list">
            <li><a href="#"><i class="social foundicon-facebook"></i></a></li>
            <li><a href="#"><i class="social foundicon-twitter"></i></a></li>
            <li><a href="#"><i class="social foundicon-pinterest"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div> <!-- End left column-->

  <div class="six columns"> <!-- Right column-->
    <div class="panel secondary recentlyPosted">
      <h4>Recently posted on our blog</h4>
      <ul class="list">
        <li>
          <a href="#">Blog post title</a>
          <p>Teaser or subtitle of blog post</p>
          </li>

        <li>
          <a href="#">Blog post title</a>
          <p>Teaser or subtitle of blog post</p>
          </li>

        <li>
          <a href="#">Blog post title</a>
          <p>Teaser or subtitle of blog post</p>
          </li>

        <li>
          <a href="#">Blog post title</a>
          <p>Teaser or subtitle of blog post</p>
        </li>
      </ul>
      <a href="#">Read More About Us →</a>
    </div>
  </div> <!-- End right column -->
</div>

app/views/pages/test.html.erb
  <div class="row">
    <div class="twelve columns">

      <!-- Navigation -->

          <ul class="nav-bar">
          <li class="active"><a href="#">Nav Item 1</a></li>
          <li><a href="#">Nav Item 2</a></li>
          <li><a href="#">Nav Item 3</a></li>
        </ul>

      <!-- End Navigation -->


      <!-- Header Content -->

        <div class="row">

          <div class="six columns">

            <img src="http://placehold.it/500x500&text=Image"><br>

          </div>


          <div class="six columns">

            <h3 class="show-for-small">Header<hr/></h3>

            <div class="panel">
              <h4 class="hide-for-small">Header<hr/></h4>
              <h5 class="subheader">Fusce ullamcorper mauris in eros dignissim molestie posuere felis blandit. Aliquam erat volutpat. Mauris ultricies posuere vehicula. Sed sit amet posuere erat. Quisque in ipsum non augue euismod dapibus non et eros. Pellentesque consectetur tempus mi iaculis bibendum. Ut vel dolor sed eros tincidunt volutpat ac eget leo.</h5>
            </div>

          <div class="row">
              <div class="six mobile-two columns">
                <div class="panel">
                  <h5>Header</h5>
                <h6 class="subheader">Praesent placerat dui tincidunt elit suscipit sed.</h6>
                <a href="#" class="small button">BUTTON TIME!</a>
                </div>
              </div>

              <div class="six mobile-two columns">
                <div class="panel">
                  <h5>Header</h5>
                <h6 class="subheader">Praesent placerat dui tincidunt elit suscipit sed.</h6>
                <a href="#" class="small button">BUTTON TIME!</a>
                </div>
              </div>
          </div>

          </div>

        </div>

      <!-- End Header Content -->


      <!-- Search Bar -->

        <div class="row">

          <div class="twelve columns">
            <div class="radius panel">

            <form>
              <div class="row collapse">

                <div class="ten mobile-three columns">
                  <input type="text" />
                </div>

                <div class="two mobile-one columns">
                  <a href="#" class="postfix button expand">Search</a>
                </div>

              </div>
            </form>

          </div>
          </div>

        </div>

      <!-- End Search Bar -->


      <!-- Thumbnails -->

        <div class="row">

          <div class="twelve show-for-small columns">
          <h3>Header</h3><hr>
        </div>

          <div class="three mobile-two columns">
            <img src="http://placehold.it/500x500&text=Thumbnail">
            <div class="panel">
              <p>Description</p>
            </div>
          </div>

          <div class="three mobile-two columns">
            <img src="http://placehold.it/500x500&text=Thumbnail">
            <div class="panel">
              <p>Description</p>
            </div>
          </div>

          <div class="three mobile-two columns">
            <img src="http://placehold.it/500x500&text=Thumbnail">
            <div class="panel">
              <p>Description</p>
            </div>
          </div>

          <div class="three mobile-two columns">
            <img src="http://placehold.it/500x500&text=Thumbnail">
            <div class="panel">
              <p>Description</p>
            </div>
          </div>

        </div>

      <!-- End Thumbnails -->


      <!-- Footer -->

        <footer class="row">
        <div class="twelve columns"><hr />
            <div class="row">

              <div class="six columns">
                  <p>&copy; Copyright no one at all. Go to town.</p>
              </div>

              <div class="six columns">
                  <ul class="link-list right">
                    <li><a href="#">Link 1</a></li>
                    <li><a href="#">Link 2</a></li>
                    <li><a href="#">Link 3</a></li>
                    <li><a href="#">Link 4</a></li>
                  </ul>
              </div>

            </div>
        </div>
      </footer>

      <!-- End Footer -->


    </div>
  </div>